// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Second(arg1) {
  return window['go']['main']['App']['Second'](arg1);
}

export function Third() {
  return window['go']['main']['App']['Third']();
}
