// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {test} from '../models';
import {main} from '../models';

export function Fruit():Promise<test.Fruit>;

export function Greet(arg1:string):Promise<string>;

export function Second(arg1:string):Promise<main.Test>;

export function Third():Promise<main.Weekday>;
